In [2]:
import pandas as pd
import numpy as np

In [5]:
excel_file = pd.ExcelFile("../data/raw/College-labor-data.xlsx")
excel_file.sheet_names

['Cover Sheet', 'unemployed', 'underemployed', 'wages', 'outcomes by major']

In [13]:
nyfed = pd.read_excel("../data/raw/College-labor-data.xlsx",
                      sheet_name='outcomes by major',
                      header=10)
nyfed.head(20)

,Major,Unemployment Rate,Underemployment Rate,Median Wage Early Career,Median Wage Mid-Career,Share with Graduate Degree
0,Agriculture,1.395,57.098,56000,80000,22.516
1,Animal and Plant Sciences,2.539,53.538,46600,79000,36.593
2,Environmental Studies,6.307,50.523,50000,80000,31.946
3,Architecture,6.844,25.669,60000,91000,40.838
4,Ethnic Studies,4.856,49.554,52000,90000,51.213
5,Communications,3.856,53.028,52000,88000,24.652
6,Journalism,2.319,43.256,49000,87000,26.278
7,Mass Media,5.158,52.125,50000,80000,19.326
8,Advertising and Public Relations,5.677,38.076,60000,92000,22.819
9,Information Systems & Management,5.979,25.637,67000,100000,27.853
10,Computer Science,6.992,19.127,87000,120000,32.691
11,General Education,2.630,28.070,45000,56000,51.683
12,Early Childhood Education,6.593,22.278,45000,52000,43.765
13,Elementary Education,1.180,16.213,45000,55000,50.596
14,Secondary Education,2.115,21.677,45300,62000,52.733
15,Special Education,0.739,16.042,46000,56000,61.091
16,Miscellaneous Education,1.089,24.543,48000,60000,59.923
17,General Engineering,4.536,31.097,75000,105000,37.058
18,Aerospace Engineering,2.176,14.709,85000,130000,45.525
19,Chemical Engineering,4.711,17.862,85000,135000,48.111

In [14]:
nyfed.shape

(74, 6)

In [15]:
nyfed.info()

<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Major                       74 non-null     str
 1   Unemployment Rate           74 non-null     float64
 2   Underemployment Rate        74 non-null     float64
 3   Median Wage Early Career    74 non-null     int64
 4   Median Wage Mid-Career      74 non-null     int64
 5   Share with Graduate Degree  74 non-null     float64
dtypes: float64(3), int64(2), str(1)
memory usage: 3.6 KB

In [16]:
nyfed.describe()

,Unemployment Rate,Underemployment Rate,Median Wage Early Career,Median Wage Mid-Career,Share with Graduate Degree
count,74.000000,74.000000,74.000000,74.000000,74.000000
mean,4.086541,38.479054,56974.324324,87216.216216,41.308514
std,1.774307,13.908829,12973.134102,19106.242450,13.771780
min,0.739000,12.781000,40000.000000,52000.000000,12.214000
25%,2.568750,26.273250,46825.000000,75000.000000,31.045750
50%,4.181000,42.918000,52000.000000,82500.000000,40.722500
75%,5.149250,49.264250,66500.000000,100000.000000,51.376750
max,7.922000,65.790000,90000.000000,135000.000000,71.939000

In [17]:
nyfed["Major"].tolist()

['Agriculture',
 'Animal and Plant Sciences',
 'Environmental Studies',
 'Architecture',
 'Ethnic Studies',
 'Communications',
 'Journalism',
 'Mass Media',
 'Advertising and Public Relations',
 'Information Systems & Management',
 'Computer Science',
 'General Education',
 'Early Childhood Education',
 'Elementary Education',
 'Secondary Education',
 'Special Education',
 'Miscellaneous Education',
 'General Engineering',
 'Aerospace Engineering',
 'Chemical Engineering',
 'Civil Engineering',
 'Computer Engineering',
 'Electrical Engineering',
 'Industrial Engineering',
 'Mechanical Engineering',
 'Miscellaneous Engineering',
 'Foreign Language',
 'Family and Consumer Sciences',
 'English Language',
 'Liberal Arts',
 'Biology',
 'Biochemistry',
 'Miscellaneous Biological Science',
 'Mathematics',
 'Interdisciplinary Studies',
 'Nutrition Sciences',
 'Leisure and Hospitality',
 'Philosophy',
 'Theology and Religion',
 'Chemistry',
 'Earth Sciences',
 'Physics',
 'Miscellaneous Physical Sciences',
 'Psychology',
 'Criminal Justice',
 'Public Policy and Law',
 'Social Services',
 'Anthropology',
 'Economics',
 'Geography',
 'Political Science',
 'Sociology',
 'General Social Sciences',
 'Construction Services',
 'Art History',
 'Fine Arts',
 'Performing Arts',
 'Commercial Art & Graphic Design',
 'Health Services',
 'Medical Technicians',
 'Nursing',
 'Pharmacy',
 'Treatment Therapy',
 'General Business',
 'Accounting',
 'Business Management',
 'Business Analytics',
 'Marketing',
 'Finance',
 'International Affairs',
 'History',
 'Engineering Technologies',
 'Miscellaneous Technologies',
 'Overall']

In [19]:
nyfed["Major"].duplicated().sum()

np.int64(0)

In [20]:
nyfed.sort_values("Unemployment Rate")[["Major", "Unemployment Rate"]]

                      Major  Unemployment Rate
15        Special Education              0.739
16  Miscellaneous Education              1.089
13     Elementary Education              1.180
0               Agriculture              1.395
26         Foreign Language              1.579
..                      ...                ...
56          Performing Arts              6.950
10         Computer Science              6.992
55                Fine Arts              7.655
21     Computer Engineering              7.783
47             Anthropology              7.922

[74 rows x 2 columns]